float sine (float angle);
float cosine (float angle);
float tangent (float angle);
float sine_inv (float val);
float cosine_inv (float val);
float tangent_inv (float val);
int add(int a,int b);
int subtract(int a,int b);
int multiply(int a,int b);
int divide(int a,int b);
int rem(int a,int b);
float exponent(int x);
float natural_logarithm(int x);
float logarithm(int x);
int power(int x,int y);
int decimal_to_bin(int decimal);
int menu_option(int s);
